//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;
using System;
using System.Collections.Generic;



namespace LockDataService.Model.Entity
{


    public partial class LoginLog
    {
        public int Id { get; set; }
        public int UserId { get; set; }

        public Nullable<int> Success { get; set; }

        public string IpAdress { get; set; }

        public string UserAgent { get; set; }

        public Nullable<System.DateTime> TimeStamp { get; set; }
    
        public virtual ClientIdentifier ClientIdentifier { get; set; }

    }
}
