//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LockDataService.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginLog
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> Success { get; set; }
        public string IpAdress { get; set; }
        public string UserAgent { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public string MobileIpAdress { get; set; }
        public string MobileUserAgent { get; set; }
        public string ClientId { get; set; }
    
        public virtual ClientIdentifier ClientIdentifier { get; set; }
    }
}
